# Generated by Django 4.1.5 on 2023-03-21 18:26

from django.db import migrations, models
import employees.staff.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('CEO', 'CEO'), ('LEAD', 'Lead'), ('SENIOR', 'Senior'), ('MIDDLE', 'Middle'), ('JUNIOR', 'Junior')], max_length=50)),
                ('date_joined', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, default=50000.0, max_digits=9)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('supervisor', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=models.SET(employees.staff.models.get_head_of_supervisor), related_name='subordinates', to='staff.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
