# Generated by Django 4.1.5 on 2023-03-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='supervisor',
            new_name='boss',
        ),
    ]
